version: '3.7'

services:
  redis:
    image: 'redis:6.2-alpine'
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - backend
  gateway:
    build: ./api-gateway
    restart: always
    hostname: gateway
    ports:
      - '3000:3000'
    env_file:
      - .env.development.local
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - backend
  book-service:
    build: ./book-service
    restart: always
    hostname: book-service
    depends_on:
      - redis
    networks:
      - backend
  magazines-service:
    build: ./magazines-service
    restart: always
    hostname: magazines-service
    depends_on:
      - redis
    networks:
      - backend
  third-service:
    build: ./third-service
    restart: always
    hostname: third-service
    depends_on:
      - redis
    networks:
      - backend

volumes:
  redis_data:

networks:
  backend:
